package cyanide3d.conf;

import java.io.*;
import java.util.Properties;

public class Config {

    private Properties properties;
    private static final Config instance = new Config();

    private Config() {
        properties = new Properties();//TODO default here
        String config = "settings.properties";
        File configFile = new File(config);
        if (configFile.isFile()) {
            try {
                properties.load(new FileInputStream(configFile));
            } catch (IOException e) {
                e.printStackTrace();
                //TODO logging
            }
        } else {
            try {
                properties.store(new FileWriter(configFile), "default autogenerated config");
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    public static Config getInstance() {
        return instance;
    }

    public String getToken() {
        return properties.getProperty("TOKEN");
    }

    public String getOwner() {
        return properties.getProperty("OWNER_ID");
    }

    public String getPrefix() {
        return properties.getProperty("PREFIX");
    }

    public void setPrefix(String prefix){
        properties.setProperty("PREFIX",prefix);
        try {
            properties.store(new FileWriter(new File("settings.properties")),null);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public String getUrl() {
        return properties.getProperty("database.url");
    }

    public String getUsename() {
        return properties.getProperty("database.username");
    }

    public String getPassword() {
        return properties.getProperty("database.password");
    }
}
